meta_product_name: "Beennie"
meta_title: "Beennie - Best plants to grow in summer<"
meta_description: "Buy any type of plant @ find advices"
meta_image: "fac.jpg" # should exist in `app/assets/images/`
