meta_product_name: "Beennie"
meta_title: "Beennie - Best plants to grow in summer<"
meta_description: "Buy any type of plant @ find advices"
meta_image: "../app/assets/images/plante.png" # should exist in `app/assets/images/`
